library(dplyr)
library(ggplot2)
library(dplyr)
library(GGally)
library(rpart)
library(rpart.plot)
library(randomForest)

> test <- read.csv("D:/Master's work/R stuff/test.csv",stringsAsFactors = FALSE)
> train <- read.csv("D:/Master's work/R stuff/train.csv",stringsAsFactors = FALSE)
> str(train)
'data.frame':   891 obs. of  12 variables:
 $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
 $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
 $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
 $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
 $ Sex        : chr  "male" "female" "female" "female" ...
 $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
 $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
 $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
 $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
 $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
 $ Cabin      : chr  "" "C85" "" "C123" ...
 $ Embarked   : chr  "S" "C" "S" "S" ...
> str(test)
'data.frame':   418 obs. of  11 variables:
 $ PassengerId: int  892 893 894 895 896 897 898 899 900 901 ...
 $ Pclass     : int  3 3 2 3 3 3 3 2 3 3 ...
 $ Name       : chr  "Kelly, Mr. James" "Wilkes, Mrs. James (Ellen Needs)" "Myles, Mr. Thomas Francis" "Wirz, Mr. Albert" ...
 $ Sex        : chr  "male" "female" "male" "male" ...
 $ Age        : num  34.5 47 62 27 22 14 30 26 18 21 ...
 $ SibSp      : int  0 1 0 0 1 0 0 1 0 2 ...
 $ Parch      : int  0 0 0 0 1 0 0 1 0 0 ...
 $ Ticket     : chr  "330911" "363272" "240276" "315154" ...
 $ Fare       : num  7.83 7 9.69 8.66 12.29 ...
 $ Cabin      : chr  "" "" "" "" ...
 $ Embarked   : chr  "Q" "S" "Q" "S" ...

> full <- bind_rows(train,test)
> LT=dim(train)[1]
> str(full)

'data.frame':   1309 obs. of  12 variables:
 $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
 $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
 $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
 $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
 $ Sex        : chr  "male" "female" "female" "female" ...
 $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
 $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
 $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
 $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
 $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
 $ Cabin      : chr  "" "C85" "" "C123" ...
 $ Embarked   : chr  "S" "C" "S" "S" ...
> colSums(is.na(full))
PassengerId    Survived      Pclass        Name         Sex         Age 
          0         418           0           0           0         263 
      SibSp       Parch      Ticket        Fare       Cabin    Embarked 
          0           0           0           1           0           0 
> colSums(full=="")
PassengerId    Survived      Pclass        Name         Sex         Age 
          0          NA           0           0           0          NA 
      SibSp       Parch      Ticket        Fare       Cabin    Embarked 
          0           0           0          NA        1014           2 
> full$Embarked[full$Embarked==""]="C"
> apply(full,2, function(x) length(unique(x)))
PassengerId    Survived      Pclass        Name         Sex         Age 
       1309           3           3        1307           2          99 
      SibSp       Parch      Ticket        Fare       Cabin    Embarked 
          7           8         929         282         187           3 
> str(full)
'data.frame':   1309 obs. of  12 variables:
 $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
 $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
 $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
 $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
 $ Sex        : chr  "male" "female" "female" "female" ...
 $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
 $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
 $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
 $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
 $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
 $ Cabin      : chr  "" "C85" "" "C123" ...
 $ Embarked   : chr  "S" "C" "S" "S" ...
> ggplot(data=full[1:LT,],aes(x=Sex,fill=Survived))+geom_bar()
> ggplot(data=full[1:LT,],aes(x=Sex,fill=Survived))+geom_bar()
TAOP<-ggplot(data=full[1:LT,],aes(x=Survived,fill=Survived))+geom_bar()
> cols<-c("Survived","Pclass","Sex","Embarked")
> for (i in cols){
+   full[,i] <- as.factor(full[,i])
+ }
#To create qqplots and qqnorm
qqplot.Age<-qplot(sample=full$Age)
qqnorm(full$Age)
#To create a Histogram have to do this first before create with lines
hist.VarableName<-ggplot(full,aes(variablename))+geom_histogram(aes(y=..density..),colour="blue",fill="white")
#Histogram With lines
hist.VarableName+stat_function(fun=dnorm,args=list(mean=mean(full$VarableName,na.rm=TRUE),sd=sd(full$VarableName,na.rm=TRUE)),colour="red", size=1)
hist.PassId+stat_function(fun=dnorm,args=list(mean=mean(full$PassengerId,na.rm=TRUE),sd=sd(full$PassengerId,na.rm=TRUE)),colour="red", size=1)
#Histogram with more than one factor
FOS<-ggplot(data = full[1:LT,],aes(x=Fare,fill=Survived))+geom_histogram(binwidth =20, position="fill")+facet_wrap(~Pclass)

#GGplot of data with and without Wrap
SOSC<-ggplot(data = full[1:LT,],aes(x=Sex,fill=Survived))+geom_bar(position="fill")+facet_wrap(~Pclass)
CSAE<-ggplot(data = full[1:LT,],aes(x=Pclass,fill=Sex))+geom_histogram(binwidth =20, position="fill", stat="count")+facet_wrap(~Embarked)
#Create a boxplot with outliers
ggplot(data = full[1:LT,],aes(x=Survived,y=Age, fill=Sex))+geom_boxplot(outlier.colour = "red")
BAVC<-ggplot(data = full[1:LT,],aes(x=Pclass,y=Age))+geom_boxplot(aes(group=Pclass, fill=factor(Pclass)), outlier.colour = "red", alpha=0.5) + scale_y_continuous(breaks = seq(min(0), max(80), by=5))
BAFS<-ggplot(data = full[1:LT,],aes(x=Fare,y=Age, fill=Sex))+geom_boxplot(outlier.colour = "red")
BASS<-ggplot(data = full[1:LT,],aes(x=Survived,y=Age, fill=Sex))+geom_boxplot(outlier.colour = "red")
BFSS<-ggplot(data = full[1:LT,],aes(x=Survived,y=Fare, fill=Sex))+geom_boxplot(outlier.colour = "red")
BFSC<-ggplot(data = full[1:LT,],aes(x=Survived,y=Fare, fill=Pclass))+geom_boxplot(outlier.colour = "red")
FOA<-ggplot(data = full[1:LT,],aes(x=Embarked,y=Fare, fill=Pclass))+geom_boxplot(outlier.colour = "red")
#Create a table of chance
t<-table(full[1:LT,]$Fare,full[1:LT,]$Survived)
for (i in 1:dim(t)[1]){
    t[i,]<-t[i,]/sum(t[i,])*100
}
t
#Chi test setup and tables
Table Name<-table(full$variablesA, full$variablesB)
chisq.test(Table Name)